spring:
  application:
    name: vehicle-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/app_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db.changelog/vehicle/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5432/app_db
    user: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver


server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
