spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: nazarovnikita322@gmail.com
    password: ltmd kkuv rnsd okfm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5432/app_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

kafka:
  group: notification_group
server:
  port: 8085