spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8088
          predicates:
            - Path=/auth/**
            - Path=/swagger-ui/**  # Добавить этот маршрут
            - Path=/v3/api-docs/**  # И этот маршрут
        - id: vehicle-service
          uri: http://localhost:8082
          predicates:
            - Path=/vehicles/**
            - Path=/swagger-ui/**  # Добавить этот маршрут
            - Path=/v3/api-docs/**  # И этот маршрут
        - id: rental-service
          uri: http://localhost:8083
          predicates:
            - Path=/rentals/**
            - Path=/swagger-ui/**  # Добавить этот маршрут
            - Path=/v3/api-docs/**  # И этот маршрут
        - id: payment-service
          uri: http://localhost:8084
          predicates:
            - Path=/card/**
            - Path=/swagger-ui/**

  main:
    web-application-type: reactive

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.web.HttpLogging: TRACE
    reactor.netty.http.server: DEBUG
    reactor.netty.http.client: DEBUG

jwt:
  secret: jsuaiqlsmdjkalskdjkjahjdjsdyuakkajsjdhuasnbdjadyaysdhkasjdhjsdugjkksas
  expirationMs: 86400000

server:
  port: 8080
  forward-headers-strategy: framework

authentication:
  enabled: true