spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: vehicle-service
          predicates:
            - Path=/vehicles/
          uri:  http://localhost:8082
        - id: rental-service
          predicates:
            - Path=/rentals/
          uri: http://localhost:8083
        - id: payment-service
          predicates:
            - Path=/payments/
          uri: http://localhost:8084
        - id : auth-service
          predicates:
            - Path=/auth/
            - Path=/users/**
          uri: http://localhost:8088

  main:
    web-application-type: reactive

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.web.HttpLogging: TRACE
    reactor.netty.http.server: DEBUG
    reactor.netty.http.client: DEBUG

jwt:
  secret: jsuaiqlsmdjkalskdjkjahjdjsdyuakkajsjdhuasnbdjadyaysdhkasjdhjsdugjkksas
  expirationMs: 86400000

server:
  port: 8080
  forward-headers-strategy: framework

authentication:
  enabled: true