spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/butilka
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


  liquibase:
    change-log: classpath:db.changelog/changelog-master.xml
    url: jdbc:postgresql://localhost:5432/butilka
    user: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
jwt:
  secret: jsuaiqlsmdjkalskdjkjahjdjsdyuakkajsjdhuasnbdjadyaysdhkasjdhjsdugjkksas
  expirationMs: 86400000
server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


logging:
  level:
    com.proj.auth.JwtAuthenticationFilter: DEBUG