spring:
  application:
    name: vehicle-service
  datasource:
    url: jdbc:postgresql://localhost:5432/butilka
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8083

vehicle:
  service:
    url: http://localhost:8082/vehicles/plate/