spring:
  kafka:
    bootstrap-servers: localhost:9092
  application:
    name: rental-service
  datasource:
    url: jdbc:postgresql://localhost:5432/app_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db_changelog/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5432/app_db
    user: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/