spring:
  kafka:
    bootstrap-servers: localhost:9092
  application:
    name: rental-service
  datasource:
    url: jdbc:postgresql://localhost:5432/butilka
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db_changelog/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5432/butilka
    user: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
server:
  port: 8083

vehicle:
  service:
    url: http://localhost:8082

jwt:
  secret: jsuaiqlsmdjkalskdjkjahjdjsdyuakkajsjdhuasnbdjadyaysdhkasjdhjsdugjkksas


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/